
package rmit.s4134401.carehome;

public enum ActionType {
    ADD_STAFF, RENAME_STAFF, SET_PASSWORD,
    ADMIT, MOVE, RX_ADD, MED_ADMIN, MED_UPDATE,
    SHIFT_ASSIGN, SHIFT_REMOVE, COMPLIANCE_CHECK, SET_DOCTOR_MINUTES
}
